### ISSUE TITLE
POPE dataset used in the experiment

### ISSUE THREAD

**Issue by sunnychenxiwang** [sangminwoo/AvisC#3]
Could you please clarify if the POPE data used in your experiment is the same as the data in the VCD. If they are the same, why are the experimental results of the VCD method in POPE different from the results in the original VCD paper.

**Comment by sangminwoo** [comment]
Hi @sunnychenxiwang,

Yes, the POPE data used in our experiment is the same as the data in the VCD. The differences in the experimental results of the VCD method in POPE compared to the original VCD paper are primarily due to variations in hyperparameters (e.g., different random seeds). In our experiments, we fixed these hyperparameters in both methods to ensure a fair comparison.

**Comment by sunnychenxiwang** [comment]
> Hi @sunnychenxiwang,
> 
> Yes, the POPE data used in our experiment is the same as the data in the VCD. The differences in the experimental results of the VCD method in POPE compared to the original VCD paper are primarily due to variations in hyperparameters (e.g., different random seeds). In our experiments, we fixed these hyperparameters in both methods to ensure a fair comparison.

Thank you for your sincere reply.
