### ISSUE TITLE
Different results in RITUAL and AVISC

### ISSUE THREAD

**Issue by zifuwan** [sangminwoo/AvisC#4]
Hi, thanks for the great work. For MME-Hallucination dataset, why the reported result in RITUAL and AVISC so different? Thanks!
<img width="734" alt="image" src="https://github.com/user-attachments/assets/3388d460-75cb-436a-9d23-b873024032c5">

**Comment by sangminwoo** [comment]
Hi @zifuwan,
Thanks for your interest in our work!

These two works have slightly different codebases and their hyperparameters (such as seed and alpha) are different.
There is minor difference in prompt design as well: we include "Please answer in one word." for RITUAL, but not for AvisC.
While we set the random seed to 42 as default for most of the results, for MME-Hallucination, we averaged the results across runs, each with a different randomly selected seed (e.g., 42, 10, 25 for AvisC and 42, 5, 16 for RITUAL --- just for example; this is not exact seed values we used).
Also note that since MME-Hallucination benchmark only contains a few hundreds of images, total scores on this benchmark vary a lot with small variations. 

Please let me know if you have further questions. I am happy to answer!

**Comment by zifuwan** [comment]
Thanks for the reply!
