### ISSUE TITLE
Difference between zeros and masking

### ISSUE THREAD

**Issue by zifuwan** [sangminwoo/AvisC#5]
Hi, what is the difference here between zeros and mask? From the code it seems like the two schemes both zero out blind tokens.
<img width="724" alt="image" src="https://github.com/user-attachments/assets/d4652f8a-70a5-412a-ad90-ed46789e1c90">

**Comment by sangminwoo** [comment]
Hi @zifuwan,

In the “Zeros / Ones / Noise”, non-blind image tokens are replaced with values of zero, one, or Gaussian noise. Contrastive decoding is then applied to heighten the impact of these non-blind tokens while diminishing the influence of blind tokens.

On the other hand, “Mask” involves masking these tokens within the attention mechanism itself, rather than directly assigning specific values to them. By doing so, we prevent the attention layers from focusing on these tokens, thereby deactivating them in an indirect way.

We recognize that the explanation of the “Mask” is not sufficient in this version of the paper, and we’ll be revising it soon.

Thank you for your attention to this!

**Comment by InstructPart** [comment]
Thanks for the reply. Is the "Mask" implementation somewhere else? From the figure "Mask" seems the same as "Zeros".

<img width="548" alt="image" src="https://github.com/user-attachments/assets/1de233f5-7cc0-4d81-99b1-5069497d39f5">

**Comment by zifuwan** [comment]
Thanks for the reply. Is the "Mask" implementation somewhere else? From the figure "Mask" seems the same as "Zeros".
<img width="499" alt="image" src="https://github.com/user-attachments/assets/1997ec19-1579-4ad1-9b49-05afd4a07057">

**Comment by sangminwoo** [comment]
Hi @zifuwan, 

It seems that we've missed updating the “mask” part of the code while organizing it for the experiment. We’ll make sure to update it soon. Conceptually, as mentioned before, "mask" approach modifes the attention mechanism itself.

Thanks a lot for reviewing the code and providing valuable feedback!

**Comment by 1jia1-oneplusone** [comment]
> Hi [@zifuwan](https://github.com/zifuwan),
> 
> It seems that we've missed updating the “mask” part of the code while organizing it for the experiment. We’ll make sure to update it soon. Conceptually, as mentioned before, "mask" approach modifes the attention mechanism itself.
> 
> Thanks a lot for reviewing the code and providing valuable feedback!

Your work is excellent, but it seems like that the "Mask" part is still not provided in the repository until today. I really want it. T_T
